// build.rs — compile-time discovery + embedding of section items and hero asset
//
// Scans assets/sections/<section>/*.md and generates const arrays in
// $OUT_DIR/items.rs that the runtime crate includes via src/content.rs.
// For each .md we extract the slug from the filename and the display title
// from the first `# Heading` line. If a sibling .png exists, its bytes are
// embedded via include_bytes! so the binary is self-contained regardless of
// runtime CWD. The landing hero (assets/hero.png) is embedded the same way.

use std::env;
use std::fs;
use std::path::Path;

const SECTIONS: [&str; 4] = ["about", "projects", "experience", "contact"];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=assets/sections");
    println!("cargo:rerun-if-changed=assets/hero.png");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("items.rs");

    let mut code = String::from("// Auto-generated by build.rs — do not edit\n\n");

    // Hero — optional; embedded as Option<&[u8]> so missing-hero stays graceful.
    let hero_path = Path::new("assets/hero.png");
    let hero_lit = if hero_path.exists() {
        let abs = hero_path.canonicalize().expect("canonicalize hero");
        format!(
            "Some(include_bytes!({}) as &'static [u8])",
            rust_str(&abs.display().to_string()),
        )
    } else {
        "None".to_string()
    };
    code.push_str(&format!(
        "pub static HERO_PNG: Option<&[u8]> = {};\n\n",
        hero_lit,
    ));

    for section in &SECTIONS {
        let dir = format!("assets/sections/{}", section);
        let mut entries: Vec<_> = fs::read_dir(&dir)
            .map(|rd| {
                rd.filter_map(Result::ok)
                    .filter(|e| {
                        e.path()
                            .extension()
                            .and_then(|s| s.to_str())
                            .map(|e| e == "md")
                            .unwrap_or(false)
                    })
                    .collect()
            })
            .unwrap_or_default();
        entries.sort_by_key(|e| e.file_name());

        let items: Vec<String> = entries
            .iter()
            .map(|e| {
                let path = e.path();
                let abs = path.canonicalize().expect("canonicalize md");
                println!("cargo:rerun-if-changed={}", abs.display());
                let slug = path
                    .file_stem()
                    .and_then(|s| s.to_str())
                    .unwrap_or("?")
                    .to_string();
                let body = fs::read_to_string(&abs).expect("read md");
                let title =
                    extract_title(&body).unwrap_or_else(|| slug.replace('-', " ").to_uppercase());
                let png_sibling = path.with_extension("png");
                let png_lit = if png_sibling.exists() {
                    let abs_png = png_sibling.canonicalize().expect("canonicalize png");
                    println!("cargo:rerun-if-changed={}", abs_png.display());
                    format!(
                        "Some(include_bytes!({}) as &'static [u8])",
                        rust_str(&abs_png.display().to_string()),
                    )
                } else {
                    "None".to_string()
                };
                format!(
                    "    Item {{ slug: {}, title: {}, body: {}, png_bytes: {} }},",
                    rust_str(&slug),
                    rust_str(&title),
                    rust_str(&body),
                    png_lit,
                )
            })
            .collect();

        code.push_str(&format!(
            "pub static {}_ITEMS: &[Item] = &[\n{}\n];\n\n",
            section.to_uppercase(),
            items.join("\n"),
        ));
    }

    fs::write(&dest, code).expect("write generated items.rs");
}

fn extract_title(md: &str) -> Option<String> {
    for line in md.lines() {
        let l = line.trim();
        if l.is_empty() {
            continue;
        }
        if let Some(rest) = l.strip_prefix("# ") {
            return Some(rest.trim().to_string());
        }
        break;
    }
    None
}

fn rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
