//! Compile-time-embedded section content.
//!
//! Item arrays are generated by `build.rs` from `assets/sections/<section>/*.md`
//! and included via the `include!` below; the file lives in `$OUT_DIR/items.rs`.

#[derive(Debug, Clone)]
pub struct Item {
    #[allow(dead_code)]
    pub slug: &'static str,
    pub title: &'static str,
    pub body: &'static str,
    pub png_path: Option<&'static str>,
}

include!(concat!(env!("OUT_DIR"), "/items.rs"));

pub fn items_for(section: crate::app::Section) -> &'static [Item] {
    use crate::app::Section::*;
    match section {
        About => ABOUT_ITEMS,
        Projects => PROJECTS_ITEMS,
        Experience => EXPERIENCE_ITEMS,
        Contact => CONTACT_ITEMS,
    }
}
