//! Compile-time-embedded section content + hero asset.
//!
//! `HERO_PNG` and per-section `*_ITEMS` arrays are generated by `build.rs` from
//! `assets/hero.png` and `assets/sections/<section>/*.md`, then included via the
//! `include!` below from `$OUT_DIR/items.rs`. Bytes are embedded with
//! `include_bytes!` so the binary works from any CWD on any machine.

#[derive(Debug, Clone)]
pub struct Item {
    #[allow(dead_code)]
    pub slug: &'static str,
    pub title: &'static str,
    pub body: &'static str,
    pub png_bytes: Option<&'static [u8]>,
}

include!(concat!(env!("OUT_DIR"), "/items.rs"));

pub fn items_for(section: crate::app::Section) -> &'static [Item] {
    use crate::app::Section::*;
    match section {
        About => ABOUT_ITEMS,
        Projects => PROJECTS_ITEMS,
        Experience => EXPERIENCE_ITEMS,
        Contact => CONTACT_ITEMS,
    }
}
