//! Compile-time-embedded section content + hero asset.
//!
//! `HERO_ASCII`, `HERO_PNG`, and per-section `*_ITEMS` arrays are generated by
//! `build.rs` from `assets/hero.{txt,png}` and `assets/sections/<section>/*.md`
//! (with optional sibling `.txt` and `.png`), then included via the `include!`
//! below from `$OUT_DIR/items.rs`. Text via build-time read + escaped literal;
//! bytes via `include_bytes!` so the binary works from any CWD on any machine.

#[derive(Debug, Clone)]
pub struct Item {
    #[allow(dead_code)]
    pub slug: &'static str,
    pub title: &'static str,
    pub body: &'static str,
    pub png_bytes: Option<&'static [u8]>,
    pub ascii: Option<&'static str>,
}

include!(concat!(env!("OUT_DIR"), "/items.rs"));

pub fn items_for(section: crate::app::Section) -> &'static [Item] {
    use crate::app::Section::*;
    match section {
        About => ABOUT_ITEMS,
        Projects => PROJECTS_ITEMS,
        Experience => EXPERIENCE_ITEMS,
        Contact => CONTACT_ITEMS,
    }
}
